### PR TITLE
fix: debug logs showing even when -d flag is not used

### LINKED ISSUE #1016: Debug logs showing even when not asking to
### Environment

Windows 11, Node 23.

### Steps to Reproduce

1. Sets some logs as logger.debug()
2. run dev server - npm run dev (without the -d for debug argument)

### Expected Behavior

will only show info level logs or higher

### Actual Behavior

DEBUG logs show in flow

### Relevant Logs/Console Output

```shell

```

### Screenshots

Image

### Motia Version

0.13.0-beta.161

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by glauberfc**
## Summary

Fixes debug logs showing even when -d flag is not used.

## Related Issues

Closes #1016 

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Refactor
- [ ] Other (please describe):

## Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/MotiaDev/motia/blob/main/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [ ] I have added tests where applicable
- [x] I have tested my changes locally
- [x] I have linked relevant issues
- [ ] I have added screenshots for UI changes (if applicable)

### CODE REVIEW

File: packages/core/src/logger.ts [hunk 1]
```diff
@@ -1,10 +1,9 @@
...
 
-const logLevel = process.env.LOG_LEVEL ?? 'info'
-
-const isDebugEnabled = logLevel === 'debug'
-const isInfoEnabled = ['info', 'debug'].includes(logLevel)
-const isWarnEnabled = ['warn', 'info', 'debug', 'trace'].includes(logLevel)
+const getLogLevel = () => process.env.LOG_LEVEL ?? 'info'
+const isDebugEnabled = () => getLogLevel() === 'debug'
+const isInfoEnabled = () => ['info', 'debug'].includes(getLogLevel())
+const isWarnEnabled = () => ['warn', 'info', 'debug', 'trace'].includes(getLogLevel())
```
Comment (ytallo) [inline packages/core/src/logger.ts]: let's use number to do it:
```
const LEVELS = {
  NOTSET:   0,
  DEBUG:    10,
  INFO:     20,
  WARNING:  30,
  ERROR:    40,
  CRITICAL: 50,
};

if (LEVELS[log] >= currentLevel)
```
